blueprint:
  name: Motion-activated Light with illuminance, sun integration, night mode, dimmable, and adjustable dim level
  description: Turn on a light when motion is detected and illuminance is below a set Lux level. The light will dim before it is turned off to signal that it has not detected motion in quite a while. Uses the sun integration to automatically detect day or night, and allows setting a temporary dimming level.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain:
          - binary_sensor
          device_class:
          - motion
          multiple: false
    lux_entity:
      name: Illuminance Sensor
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - illuminance
          multiple: false
    lux_level:
      name: Illuminance level
      description: If lux is below this value and motion is detected, the light will turn on.
      default: 100
      selector:
        number:
          min: 0.0
          max: 3000.0
          step: 1.0
          mode: slider
    light_target:
      name: Light
      selector:
        target:
          entity:
          - domain:
            - light
    dim_time:
      name: Dim light
      description: The light will start dimming this many seconds before it is turned off if no motion has been detected to signal that the light will soon turn off.
      default: 30
      selector:
        number:
          min: 0.0
          max: 120.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    no_motion_wait_day:
      name: Wait time (day)
      description: Time to leave the light on after last motion is detected during the day.
      default: 300
      selector:
        number:
          min: 0.0
          max: 600.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    no_motion_wait_night:
      name: Wait time (night)
      description: Time to leave the light on after last motion is detected during the night.
      default: 120
      selector:
        number:
          min: 0.0
          max: 600.0
          unit_of_measurement: seconds
          step: 1.0
          mode: slider
    dim_value:
      name: Dim value
      description: Temporary dim level to set when the light is dimming before turning off. The light will start from its default brightness the next time it turns on.
      default: 10
      selector:
        number:
          min: 1
          max: 255
          step: 1
          mode: slider
  source_url: https://github.com/alx-uta/Home-Assistant-Blueprints/blob/main/motion-illuminance-dimmable-nightmode.yaml
mode: restart
max_exceeded: silent
variables:
  local_motion_delay_day: !input no_motion_wait_day
  local_motion_delay_night: !input no_motion_wait_night
  local_motion_dim_time: !input dim_time
  local_dim_value: !input dim_value
trigger:
  platform: state
  entity_id: !input motion_entity
  from: 'off'
  to: 'on'
condition:
  condition: numeric_state
  entity_id: !input lux_entity
  below: !input lux_level
action:
- service: light.turn_on
  target: !input light_target
- wait_for_trigger:
    platform: state
    entity_id: !input motion_entity
    from: 'on'
- delay: >
    {% if is_state('sun.sun', 'below_horizon') %}
      {{ local_motion_delay_night - local_motion_dim_time }}
    {% else %}
      {{ local_motion_delay_day - local_motion_dim_time }}
    {% endif %}
- service: light.turn_on
  target: !input light_target
  data:
    brightness: "{{ local_dim_value }}"
- delay: "{{ local_motion_dim_time }}"
- service: light.turn_off
  target: !input light_target
