blueprint:
  name: Motion-activated Light with brightness restore and timing fixes
  description: Turn on a light when motion is detected and illuminance is below a set Lux level. Includes brightness restoration and precise timing.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    lux_entity:
      name: Illuminance Sensor
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    lux_level:
      name: Illuminance Level
      default: 100
      selector:
        number:
          min: 0
          max: 3000
          step: 1
    light_target:
      name: Light
      selector:
        target:
          entity: light
    dim_time:
      name: Dim Time
      default: 15
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: seconds
    no_motion_wait_day:
      name: Wait Time (Day)
      default: 30
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds
    no_motion_wait_night:
      name: Wait Time (Night)
      default: 15
      selector:
        number:
          min: 0
          max: 600
          unit_of_measurement: seconds
    dim_value:
      name: Dim Value
      default: 10
      selector:
        number:
          min: 1
          max: 255
  variables:
    motion_wait_day: !input no_motion_wait_day
    motion_wait_night: !input no_motion_wait_night
    dim_time: !input dim_time
    dim_value: !input dim_value
  trigger:
    platform: state
    entity_id: !input motion_entity
    from: 'off'
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: !input lux_entity
    below: !input lux_level
  action:
    - service: light.turn_on
      target: !input light_target
      data:
        brightness: >
          {{ state_attr(target.entity_id, 'brightness') | default(255) }}
    - wait_for_trigger:
        platform: state
        entity_id: !input motion_entity
        from: 'on'
    - delay: >
        {% if is_state('sun.sun', 'below_horizon') %}
          {{ motion_wait_night - dim_time }}
        {% else %}
          {{ motion_wait_day - dim_time }}
        {% endif %}
    - service: light.turn_on
      target: !input light_target
      data:
        brightness: "{{ dim_value }}"
    - delay: "{{ dim_time }}"
    - service: light.turn_off
      target: !input light_target
